server:
  port: ${PORT:8083}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

target: local

spring:
 config:
   activate:
     on-profile: cloud-dev
 datasource:
   url: 'jdbc:postgresql://${DB_HOST:127.0.0.1}/${DB_DATABASE:quote_db}'
   username: '${DB_USER:user}'
   password: '${DB_PASS:password}'
 jpa:
   properties:
     hibernate:
       jdbc:
         lob:
           non_contextual_creation: true
       dialect: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
     ddl-auto: update

#  datasource:
#    url: jdbc:h2:mem:test
#    username: user
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console.enabled: true
---
spring:
 config:
   activate:
     on-profile: cloud-prod
 datasource:
   url: 'jdbc:postgresql://${DB_HOST:127.0.0.1}/${DB_DATABASE:quote_db}'
   username: '${DB_USER:user}'
   password: '${DB_PASS:password}'
 jpa:
   properties:
     hibernate:
       jdbc:
         lob:
           non_contextual_creation: true
       dialect: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
     ddl-auto: none